# Site settings
title: Lightbox samples
description: > # this means to ignore newlines until "baseurl:"
  lightbox scripts samples.
baseurl: /lightbox-sample # github pages向け設定
url: "" # the base hostname & protocol for your site, e.g. http://example.com
placeholder:
  youtube: 
    - 9ZfN87gSjvI
  googlemap:
    - https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d8914.752749448939!2d139.69967396300015!3d35.690515634467474!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x1c32a1f1ecacfdd5!2z5paw5a6_6aeF!5e0!3m2!1sja!2sjp!4v1469005122314

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
